### ISSUE TITLE
Check Webscraping Functions

### ISSUE THREAD

**Issue by nfmcclure** [nfmcclure/NBA_Predictions_V4#1]
The webscraping functions are ~1.5 years old.  Regular maintenance must be performed to make sure they are all performing well.

**Comment by rmooretrans** [comment]
Is it possible to update the webscraping ? I've tried to figure it out but just can't. Thx.

**Comment by WillPanarese** [comment]
Just learned python and am trying to make an nba predictions model similar to this. Just want to learn how to do it then add my own touch to the model. Having trouble scraping current data from websites. Please let me know if you could help me out.

**Comment by nfmcclure** [comment]
I really want to do this, but will not have the time until the NBA season is over.  The amount of work entailed depends on how the structure of the sites has changed.  If it's just a re-format of the data, then it's probably just a days effort.  If it's massively changed or put behind a javascript function, then it may require finding a completely different source of data, which also would imply that the modeling would have to change as well.

I'll try to put in a few hours this month to see if I can gauge the changes and see what it would take.

**Comment by WillPanarese** [comment]
Thanks for getting back to me so quickly. Totally understand that it takes a lot of work. I am creating an NBA predictions model using python for an independent study, but am having trouble with even just simply scraping the correct data to make even a basic model. If there is another github thread or tutorial you think would be helpful, let me know. I am new to coding, but understand python pretty well. Just looking to get a grasp on how to make a pretty basic model and then build off that once I understand more. The trouble I’m having currently is the data scraping, so if you have any resources that could help that would be greatly appreciated.

**Comment by WillPanarese** [comment]
I am mainly focusing on tweaking code from published models, not really going to create my own model entirely from scratch. Just need to understand better how to tweak and adjust these models for current data.

**Comment by WillPanarese** [comment]
I actually found a way to use the nba_py API as a good scraper, so just looking for a way to use that to create a model rather than calling from basketball reference. any advice would be helpful

**Comment by nfmcclure** [comment]
Webscraping has been updated.  But there is now remaining work to tie the resulting dataframes into the modeling training/testing/prediction.  I'm off for Thx-giving break and will put in some time to get this all running by the end of the month.

I'm creating a separate issue to get the remainder of the program working with the updated data/web scraping now in place.
